version: '2.2'

services:

  nginx:

    build: ./requirements/nginx #where to find the Dockerfile
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"


